services:
  sugarcane-app:
    build: .
    container_name: sugarcane-app
    ports:
      - "8123:8123"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
