services:
  sugarcane-app:
    build: .
    container_name: sugarcane-app
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
